# Generated by Django 5.0.3 on 2024-03-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlists',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
