# Generated by Django 5.0.3 on 2024-03-29 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('links', '0002_rename_links_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('views', models.IntegerField()),
                ('length', models.IntegerField()),
                ('channel', models.CharField(max_length=255)),
                ('channel_url', models.CharField(max_length=255)),
                ('video_id', models.CharField(max_length=255)),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.link')),
            ],
        ),
    ]
