# Generated by Django 5.0.3 on 2024-03-30 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_playlists_id'),
        ('links_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linksprocess',
            name='link_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link_process', to='links.link'),
        ),
    ]
