# Generated by Django 5.0.3 on 2024-03-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links_process', '0002_alter_linksprocess_link_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='linksprocess',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
