# Generated by Django 5.0.3 on 2024-03-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('playlists', '0002_alter_playlists_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('youtube_id', models.CharField(max_length=100)),
                ('links_process_status', models.BooleanField(verbose_name=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('playlists_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlists')),
            ],
        ),
    ]
