# Generated by Django 5.0.3 on 2024-03-29 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
        ('playlists', '0002_alter_playlists_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
