# Generated by Django 5.0.3 on 2024-03-30 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_rename_links_link'),
        ('playlists', '0003_rename_playlists_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='playlists_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='playlists.playlist'),
        ),
    ]
