# Generated by Django 5.0.3 on 2024-03-30 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_alter_link_playlists_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
