# Generated by Django 5.0.3 on 2024-03-31 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0005_remove_link_links_process_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='view_player',
            field=models.IntegerField(default=0),
        ),
    ]
